from tkinter import *
root = Tk()
root.title("Конвертер валют")
root.geometry("850x600")
root.resizable(width=False, height=False)
root.config(bg='gray')
PRV = Label(root, text='', font=('Rubik Spray Paint', 18), bg='gray')
PRV.place(x=60, y=480)
bcst = Label(root, text='', font=('Rubik Spray Paint', 18), bg='gray')
bcst.place(x=300, y=480)
efrt = Label(root, text='', font=('Rubik Spray Paint', 18), bg='gray')
efrt.place(x=450, y=480)
pont = Label(root, text='', font=('Rubik Spray Paint', 18), bg='gray')
pont.place(x=575, y=480)
def rbl():
    l_logo.config(text='Введите количество рублей:')
    entry1 = Entry(root, width=25)
    entry1.place(x=350, y=310)
    def r():
        text = str(entry1.get()) + ' Рублей:'
        bcs = str(int(entry1.get())//83) + ('$')
        efr = str(int(entry1.get())//95) + ('€')
        pon = str(int(entry1.get())//112) + ('£')
        PRV.config(text=text, bg='white')
        bcst.config(text=bcs, bg='white')
        efrt.config(text=efr, bg='white')
        pont.config(text=pon, bg='white')
    btn1 = Button(root, command = r, text='Конвертировать', width=25, height=3, bg='green')
    btn1.place(x=335, y=350)
def dol():
    l_logo.config(text='Введите количество долларов:')
    entry2 = Entry(root, width=25)
    entry2.place(x=350, y=310)
    def d():
        text = str(entry2.get()) + ' Долларов:'
        bcs = str(int(entry2.get())//0.012) + ('₽')
        efr = str(int(entry2.get())//1.15) + ('€')
        pon = str(int(entry2.get())//1.35) + ('£')
        PRV.config(text=text, bg='white')
        bcst.config(text=bcs, bg='white')
        efrt.config(text=efr, bg='white')
        pont.config(text=pon, bg='white')
    btn2 = Button(root, command = d, text='Конвертировать', width=25, height=3, bg='green')
    btn2.place(x=335, y=350)
def evr():
    l_logo.config(text='Введите количество евро:')
    entry3 = Entry(root, width=25)
    entry3.place(x=350, y=310)
    def e():
        text = str(entry3.get()) + ' Евро:'
        bcs = str(int(entry3.get())//0.01) + ('₽')
        efr = str(int(entry3.get())//0.87) + ('$')
        pon = str(int(entry3.get())//1.17) + ('£')
        PRV.config(text=text, bg='white')
        bcst.config(text=bcs, bg='white')
        efrt.config(text=efr, bg='white')
        pont.config(text=pon, bg='white')
    btn3 = Button(root, command = e, text='Конвертировать', width=25, height=3, bg='green')
    btn3.place(x=335, y=350)
def ppnd():
    l_logo.config(text='Введите количество фунтов:')
    entry4 = Entry(root, width=25)
    entry4.place(x=350, y=310)
    def p():
        text = str(entry4.get()) + ' Фунтов:'
        bcs = str(int(entry4.get()) // 0.009) + ('₽')
        efr = str(int(entry4.get()) // 0.74) + ('$')
        pon = str(int(entry4.get()) // 0.85) + ('€')
        PRV.config(text=text, bg='white')
        bcst.config(text=bcs, bg='white')
        efrt.config(text=efr, bg='white')
        pont.config(text=pon, bg='white')
    btn4 = Button(root, command=p, text='Конвертировать', width=25, height=3, bg='green')
    btn4.place(x=335, y=350)
l_logo = Label(root, font=('Arial', 25), bg = 'white', fg = 'black')
name= Label(root, text='Конвертация валют', font = ('Rubik Spray Paint', 30), bg='white', fg='black')
name.pack()
minitext = Label(root, text='Выберите валюту перевода:', font=('Arial', 15), bg='white', fg='black')
minitext.place(x=0,y=70)
ruble = Button(root, text = '₽', command = rbl, font = ('Arial', 25), bg='white', fg='black')
ruble.place(x=0,y=100)
usd = Button(root, text = '$', command = dol, font = ('Arial', 25), bg='white', fg='black')
usd.place(x=50,y=100)
euro = Button(root, text = '€', command = evr, font = ('Arial', 25), bg='white', fg='black')
euro.place(x=100,y=100)
gbp = Button(root, text = '£', command = ppnd, font = ('Arial', 25), bg='white', fg='black')
gbp.place(x=150,y=100)
l_logo.place(x=210,y=250)
root.mainloop()
